services:
  node-red:
    build: .
    container_name: node-red-contrib-uhppoted-examples
    environment:
      - FLOWS=/node-red-contrib-uhppoted/examples/examples.json
    volumes:
      - ../../:/node-red-contrib-uhppoted
    ports:
      - "1880:1880"
    tty: true
    stdin_open: true
    restart: "no"
    network_mode: "bridge"
